/* IFC eleman tiplerinin buildingSMART resmi tanimlarindan sadelestirilmis,
   cok dilli aciklamalari. src/utils/ifcTypes.js'teki tip kodlariyla eslesir.
   Kaynak: https://ifc43-docs.standards.buildingsmart.org (IFC 4.3.2 semantic definitions) */

const tr = {
  IFCPROJECT: 'Modeldeki tüm bilgilerin ait olduğu üst düzey proje çerçevesi; birim, koordinat sistemi gibi genel ayarları taşır.',
  IFCSITE: 'Projenin üzerine inşa edildiği arsa/arazi parçası; konum ve yükseklik referansını tanımlar.',
  IFCBUILDING: 'Bina; saha, kat ve mekanlarla birlikte modelin temel mekansal iskelet elemanı.',
  IFCBUILDINGSTOREY: 'Bina katı; birbirine yakın yükseklikteki mekanların toplandığı yatay seviye.',
  IFCSPACE: 'Bir işlevi barındıran, sınırları belirli iç mekan (oda, koridor, hacim).',
  IFCWALL: 'Düşeye yakın, mekanları ayıran/sınırlayan duvar elemanı; taşıyıcı olması zorunlu değildir.',
  IFCWALLSTANDARDCASE: 'Sabit kalınlıklı, katmanlı malzeme kesitine sahip standart tip duvar.',
  IFCSLAB: 'Döşeme; bir mekanın altını (kat döşemesi) veya üstünü (çatı döşemesi) yatay olarak kapatan yapı elemanı.',
  IFCROOF: 'Binanın üst kısmını hava koşullarından koruyan çatı elemanı.',
  IFCCOLUMN: 'Genelde düşey, üstteki yükü altındaki elemanlara aktaran taşıyıcı veya mimari kolon.',
  IFCBEAM: 'Genelde yatay, eğilmeye karşı direnç göstererek yük taşıyan kiriş elemanı.',
  IFCDOOR: 'İnsan, eşya veya araç geçişini kontrollü şekilde sağlayan kapı elemanı.',
  IFCWINDOW: 'Doğal ışık ve hava girişini sağlayan, sabit veya açılabilir kanatlı pencere elemanı.',
  IFCSTAIR: 'Bir kattan farklı seviyedeki başka bir kata yürüyerek geçişi sağlayan merdiven bütünü.',
  IFCSTAIRFLIGHT: 'Sahanlıkla bölünmemiş, tek bir "kol" halindeki merdiven basamakları grubu.',
  IFCRAILING: 'Düşme veya çarpmayı önlemek amacıyla dolaşım alanlarının kenarına yerleştirilen korkuluk.',
  IFCFURNISHINGELEMENT: 'Taşınabilir veya sabit (gömme) mobilya ve donatı elemanlarının genel adı.',
  IFCPLATE: 'Sabit kalınlıklı, düz/eğik yüzeyler için kullanılan levha elemanı (örn. cephe paneli, metal levha).',
  IFCMEMBER: 'Kolon veya kiriş gibi daha özel bir sınıfa girmeyen, yük taşıyabilen genel taşıyıcı eleman.',
  IFCCOVERING: 'Başka bir elemanın yüzeyini kaplayan, ona bağımlı kaplama katmanı (örn. asma tavan, döşeme kaplaması).',
  IFCFOOTING: 'Yapının yükünü zemine yayarak aktaran temel elemanı.',
  IFCBUILDINGELEMENTPROXY: 'Henüz özel bir IFC tipiyle tanımlanmamış, genel amaçlı yer tutucu yapı elemanı.',
  IFCFLOWSEGMENT: 'Bir tesisat (HVAC, sıhhi tesisat vb.) hattının düz bir bölümünü temsil eden boru/kanal parçası.',
  IFCFLOWTERMINAL: 'Tesisat sisteminin dış ortamla buluştuğu uç nokta (örn. musluk, hava çıkışı, gider).',
  IFCGROUP: 'Kendi konumu ve geometrisi olmayan, nesneleri mantıksal olarak bir araya toplayan grup.',
};

const en = {
  IFCPROJECT: 'The top-level project context that all model information belongs to; carries shared settings like units and coordinate systems.',
  IFCSITE: 'The plot of land the project is built on; defines its location and elevation reference.',
  IFCBUILDING: 'A building; together with site, storeys and spaces it forms the model\'s basic spatial structure.',
  IFCBUILDINGSTOREY: 'A building storey; a horizontal level that groups spaces at a similar height.',
  IFCSPACE: 'A bounded interior area or volume that serves a function (a room, corridor, or void).',
  IFCWALL: 'A vertical or near-vertical element that separates or bounds spaces; not required to be load-bearing.',
  IFCWALLSTANDARDCASE: 'A standard wall type with constant thickness and a layered material cross-section.',
  IFCSLAB: 'A slab; a flat structural element that closes a space from below (floor) or above (roof).',
  IFCROOF: 'The covering at the top of a building that protects it from the weather.',
  IFCCOLUMN: 'A usually vertical member that carries the load of the structure above down to elements below.',
  IFCBEAM: 'A usually horizontal member that carries load mainly by resisting bending.',
  IFCDOOR: 'A building element that provides controlled passage for people, goods or vehicles.',
  IFCWINDOW: 'A building element that provides daylight and fresh air, with fixed or opening panels.',
  IFCSTAIR: 'The full stair assembly that lets people walk between floors at different levels.',
  IFCSTAIRFLIGHT: 'A single uninterrupted run of stair steps, not broken by a landing.',
  IFCRAILING: 'A protective barrier placed along circulation areas to prevent falling or collision.',
  IFCFURNISHINGELEMENT: 'General term for furniture-type objects, whether movable or built-in.',
  IFCPLATE: 'A flat element of constant thickness, such as a cladding or metal panel.',
  IFCMEMBER: 'A general load-carrying structural element that doesn\'t fit a more specific type like beam or column.',
  IFCCOVERING: 'A finishing layer that depends on and covers another element, such as a suspended ceiling or flooring.',
  IFCFOOTING: 'A foundation element that spreads a structure\'s load into the ground.',
  IFCBUILDINGELEMENTPROXY: 'A generic placeholder element used when no specific IFC type applies yet.',
  IFCFLOWSEGMENT: 'A straight section of a building services system, such as a duct or pipe run.',
  IFCFLOWTERMINAL: 'The end point where a services system meets its surroundings, such as a tap, outlet or drain.',
  IFCGROUP: 'A logical collection of objects with no position or shape of its own.',
};

const de = {
  IFCPROJECT: 'Der übergeordnete Projektrahmen, dem alle Modellinformationen zugeordnet sind; enthält gemeinsame Einstellungen wie Einheiten und Koordinatensystem.',
  IFCSITE: 'Das Grundstück, auf dem das Projekt errichtet wird; definiert Lage- und Höhenreferenz.',
  IFCBUILDING: 'Ein Gebäude; bildet zusammen mit Grundstück, Geschossen und Räumen die grundlegende räumliche Struktur des Modells.',
  IFCBUILDINGSTOREY: 'Ein Geschoss; eine horizontale Ebene, die Räume ähnlicher Höhe zusammenfasst.',
  IFCSPACE: 'Ein begrenzter Innenbereich mit einer Funktion (Raum, Flur oder Hohlraum).',
  IFCWALL: 'Ein senkrechtes oder nahezu senkrechtes Element, das Räume trennt oder begrenzt; muss nicht tragend sein.',
  IFCWALLSTANDARDCASE: 'Eine Standardwand mit konstanter Dicke und geschichtetem Materialquerschnitt.',
  IFCSLAB: 'Eine Platte; ein flaches Bauteil, das einen Raum von unten (Geschossdecke) oder oben (Dachplatte) abschließt.',
  IFCROOF: 'Die oberste Abdeckung eines Gebäudes, die es vor Witterung schützt.',
  IFCCOLUMN: 'Ein meist senkrechtes Bauteil, das die Last der oberen Konstruktion nach unten abträgt.',
  IFCBEAM: 'Ein meist waagrechtes Bauteil, das Lasten hauptsächlich durch Biegewiderstand trägt.',
  IFCDOOR: 'Ein Bauelement, das den kontrollierten Durchgang für Personen, Güter oder Fahrzeuge ermöglicht.',
  IFCWINDOW: 'Ein Bauelement für Tageslicht und Frischluft, mit festen oder öffenbaren Flügeln.',
  IFCSTAIR: 'Die gesamte Treppenanlage, die den Übergang zwischen unterschiedlichen Geschossebenen ermöglicht.',
  IFCSTAIRFLIGHT: 'Ein einzelner, nicht durch einen Treppenabsatz unterbrochener Treppenlauf.',
  IFCRAILING: 'Ein Geländer entlang von Verkehrsflächen, das vor Absturz oder Zusammenstoß schützt.',
  IFCFURNISHINGELEMENT: 'Sammelbegriff für Möbelobjekte, ob beweglich oder fest eingebaut.',
  IFCPLATE: 'Ein flaches Bauteil konstanter Dicke, z. B. eine Fassaden- oder Metallplatte.',
  IFCMEMBER: 'Ein allgemeines tragendes Bauteil, das keiner spezielleren Kategorie wie Stütze oder Balken entspricht.',
  IFCCOVERING: 'Eine Belagsschicht, die von einem anderen Bauteil abhängt und dieses bedeckt, z. B. abgehängte Decke oder Bodenbelag.',
  IFCFOOTING: 'Ein Fundamentbauteil, das die Last eines Bauwerks in den Boden ableitet.',
  IFCBUILDINGELEMENTPROXY: 'Ein generisches Platzhalterelement für Bauteile ohne spezifischen IFC-Typ.',
  IFCFLOWSEGMENT: 'Ein gerader Abschnitt einer Gebäudetechnikleitung, z. B. Rohr- oder Kanalstück.',
  IFCFLOWTERMINAL: 'Der Endpunkt, an dem ein Anlagensystem auf die Umgebung trifft, z. B. Wasserhahn, Luftauslass oder Abfluss.',
  IFCGROUP: 'Eine logische Zusammenstellung von Objekten ohne eigene Position oder Form.',
};

const ar = {
  IFCPROJECT: 'سياق المشروع الأعلى الذي تنتمي إليه جميع معلومات النموذج؛ يحمل إعدادات مشتركة مثل الوحدات ونظام الإحداثيات.',
  IFCSITE: 'قطعة الأرض التي يُبنى عليها المشروع؛ تحدد موقعها ومرجع الارتفاع.',
  IFCBUILDING: 'مبنى؛ يشكّل مع الموقع والطوابق والمساحات البنية المكانية الأساسية للنموذج.',
  IFCBUILDINGSTOREY: 'طابق في المبنى؛ مستوى أفقي يجمع المساحات ذات الارتفاع المتقارب.',
  IFCSPACE: 'منطقة أو حجم داخلي محدود له وظيفة معينة (غرفة، ممر، أو فراغ).',
  IFCWALL: 'عنصر رأسي أو شبه رأسي يفصل أو يحد المساحات؛ ليس بالضرورة أن يكون حاملاً.',
  IFCWALLSTANDARDCASE: 'جدار من النوع القياسي بسماكة ثابتة ومقطع مواد متعدد الطبقات.',
  IFCSLAB: 'بلاطة؛ عنصر مسطح يغلق المساحة من الأسفل (بلاطة أرضية) أو من الأعلى (بلاطة سقف).',
  IFCROOF: 'الغطاء العلوي للمبنى الذي يحميه من تأثيرات الطقس.',
  IFCCOLUMN: 'عنصر رأسي غالباً ينقل حمل الإنشاء العلوي إلى العناصر السفلية.',
  IFCBEAM: 'عنصر أفقي غالباً يتحمل الحمل بشكل أساسي عن طريق مقاومة الانحناء.',
  IFCDOOR: 'عنصر إنشائي يوفر مروراً متحكماً به للأشخاص أو البضائع أو المركبات — الباب.',
  IFCWINDOW: 'عنصر إنشائي يوفر الإضاءة الطبيعية والهواء النقي، بألواح ثابتة أو قابلة للفتح — النافذة.',
  IFCSTAIR: 'التجميع الكامل للسلم الذي يتيح الانتقال سيراً بين طوابق بمستويات مختلفة.',
  IFCSTAIRFLIGHT: 'مجموعة متصلة من درجات السلم غير مقطوعة ببسطة.',
  IFCRAILING: 'حاجز حماية يوضع على طول مناطق الحركة لمنع السقوط أو الاصطدام.',
  IFCFURNISHINGELEMENT: 'مصطلح عام لعناصر الأثاث، سواء كانت متحركة أو مثبتة.',
  IFCPLATE: 'عنصر مسطح بسماكة ثابتة، مثل لوح واجهة أو معدني.',
  IFCMEMBER: 'عنصر إنشائي حامل عام لا ينتمي إلى نوع أكثر تحديداً مثل العمود أو الجائز.',
  IFCCOVERING: 'طبقة تشطيب تعتمد على عنصر آخر وتغطيه، مثل السقف المعلق أو تغطية الأرضية.',
  IFCFOOTING: 'عنصر أساس يوزع حمل المنشأ وينقله إلى التربة.',
  IFCBUILDINGELEMENTPROXY: 'عنصر عام مؤقت يُستخدم عندما لا يوجد بعد نوع IFC محدد له.',
  IFCFLOWSEGMENT: 'جزء مستقيم من شبكة تمديدات (تكييف، سباكة، إلخ)، مثل قطعة أنبوب أو مجرى هواء.',
  IFCFLOWTERMINAL: 'النقطة الطرفية التي تلتقي فيها شبكة التمديدات بالبيئة المحيطة، مثل صنبور أو مخرج هواء أو مصرف.',
  IFCGROUP: 'تجميع منطقي للعناصر لا يملك موضعاً أو شكلاً خاصاً به.',
};

const ru = {
  IFCPROJECT: 'Верхнеуровневый контекст проекта, к которому относится вся информация модели; хранит общие настройки — единицы измерения, систему координат.',
  IFCSITE: 'Земельный участок, на котором строится проект; задаёт положение и высотную привязку.',
  IFCBUILDING: 'Здание; вместе с площадкой, этажами и помещениями образует базовую пространственную структуру модели.',
  IFCBUILDINGSTOREY: 'Этаж здания; горизонтальный уровень, объединяющий помещения близкой высоты.',
  IFCSPACE: 'Ограниченная внутренняя область или объём с определённой функцией (комната, коридор, полость).',
  IFCWALL: 'Вертикальный или близкий к вертикальному элемент, разделяющий или ограничивающий помещения; не обязательно несущий.',
  IFCWALLSTANDARDCASE: 'Стандартная стена постоянной толщины со слоистым составом материалов.',
  IFCSLAB: 'Плита; плоский элемент, закрывающий помещение снизу (перекрытие) или сверху (кровельная плита).',
  IFCROOF: 'Верхнее покрытие здания, защищающее его от погодных воздействий.',
  IFCCOLUMN: 'Обычно вертикальный элемент, передающий нагрузку от верхней конструкции к нижним элементам.',
  IFCBEAM: 'Обычно горизонтальный элемент, воспринимающий нагрузку главным образом за счёт сопротивления изгибу.',
  IFCDOOR: 'Элемент здания, обеспечивающий контролируемый проход людей, грузов или транспорта.',
  IFCWINDOW: 'Элемент здания для естественного освещения и вентиляции, с глухими или открывающимися створками.',
  IFCSTAIR: 'Вся лестничная конструкция, обеспечивающая переход между этажами разного уровня.',
  IFCSTAIRFLIGHT: 'Один непрерывный марш лестничных ступеней, не прерываемый площадкой.',
  IFCRAILING: 'Ограждение вдоль путей движения, защищающее от падения или столкновения.',
  IFCFURNISHINGELEMENT: 'Общее название предметов мебели — как переносных, так и встроенных.',
  IFCPLATE: 'Плоский элемент постоянной толщины, например фасадная или металлическая панель.',
  IFCMEMBER: 'Общий несущий элемент, не относящийся к более конкретному типу, например колонне или балке.',
  IFCCOVERING: 'Отделочный слой, зависящий от другого элемента и покрывающий его, например подвесной потолок или напольное покрытие.',
  IFCFOOTING: 'Элемент фундамента, распределяющий нагрузку конструкции на грунт.',
  IFCBUILDINGELEMENTPROXY: 'Универсальный элемент-заглушка для случаев, когда конкретный тип IFC ещё не определён.',
  IFCFLOWSEGMENT: 'Прямой участок инженерной сети, например отрезок трубы или воздуховода.',
  IFCFLOWTERMINAL: 'Конечная точка, где инженерная система соединяется с окружающей средой, например кран, воздуховыпуск или слив.',
  IFCGROUP: 'Логическое объединение объектов без собственного положения или формы.',
};

const es = {
  IFCPROJECT: 'El contexto de proyecto de nivel superior al que pertenece toda la información del modelo; contiene ajustes comunes como unidades y sistema de coordenadas.',
  IFCSITE: 'El terreno sobre el que se construye el proyecto; define su ubicación y referencia de altura.',
  IFCBUILDING: 'Un edificio; junto con el terreno, las plantas y los espacios forma la estructura espacial básica del modelo.',
  IFCBUILDINGSTOREY: 'Una planta del edificio; un nivel horizontal que agrupa espacios de altura similar.',
  IFCSPACE: 'Un área o volumen interior delimitado con una función (una habitación, pasillo o hueco).',
  IFCWALL: 'Un elemento vertical o casi vertical que separa o delimita espacios; no tiene por qué ser portante.',
  IFCWALLSTANDARDCASE: 'Un muro estándar de espesor constante con una sección de materiales en capas.',
  IFCSLAB: 'Una losa; un elemento plano que cierra un espacio por abajo (forjado) o por arriba (losa de cubierta).',
  IFCROOF: 'La cubierta superior del edificio que lo protege de las inclemencias del tiempo.',
  IFCCOLUMN: 'Un elemento normalmente vertical que transmite la carga de la estructura superior a los elementos inferiores.',
  IFCBEAM: 'Un elemento normalmente horizontal que resiste la carga principalmente por flexión.',
  IFCDOOR: 'Un elemento constructivo que permite el paso controlado de personas, mercancías o vehículos.',
  IFCWINDOW: 'Un elemento constructivo para luz natural y ventilación, con hojas fijas o practicables.',
  IFCSTAIR: 'El conjunto completo de la escalera que permite pasar caminando entre plantas de distinto nivel.',
  IFCSTAIRFLIGHT: 'Un tramo continuo de peldaños de escalera, sin interrupción por un rellano.',
  IFCRAILING: 'Una barandilla situada junto a zonas de circulación para evitar caídas o colisiones.',
  IFCFURNISHINGELEMENT: 'Término general para objetos de mobiliario, ya sean móviles o empotrados.',
  IFCPLATE: 'Un elemento plano de espesor constante, como un panel de fachada o metálico.',
  IFCMEMBER: 'Un elemento estructural genérico que no encaja en un tipo más específico como pilar o viga.',
  IFCCOVERING: 'Una capa de acabado que depende de otro elemento y lo recubre, como un falso techo o un pavimento.',
  IFCFOOTING: 'Un elemento de cimentación que reparte la carga de la estructura hacia el terreno.',
  IFCBUILDINGELEMENTPROXY: 'Un elemento genérico provisional usado cuando aún no existe un tipo IFC específico.',
  IFCFLOWSEGMENT: 'Un tramo recto de una instalación (climatización, fontanería, etc.), como un tubo o conducto.',
  IFCFLOWTERMINAL: 'El punto final donde una instalación se conecta con el entorno, como un grifo, una salida de aire o un desagüe.',
  IFCGROUP: 'Una agrupación lógica de objetos sin posición ni forma propia.',
};

const fr = {
  IFCPROJECT: 'Le contexte de projet de niveau supérieur auquel appartiennent toutes les informations du modèle ; contient les réglages communs comme les unités et le système de coordonnées.',
  IFCSITE: 'Le terrain sur lequel le projet est construit ; définit sa localisation et sa référence d\'altitude.',
  IFCBUILDING: 'Un bâtiment ; avec le terrain, les étages et les espaces, il forme la structure spatiale de base du modèle.',
  IFCBUILDINGSTOREY: 'Un étage du bâtiment ; un niveau horizontal regroupant des espaces de hauteur similaire.',
  IFCSPACE: 'Une aire ou un volume intérieur délimité ayant une fonction (une pièce, un couloir ou un vide).',
  IFCWALL: 'Un élément vertical ou quasi vertical qui sépare ou délimite des espaces ; il n\'est pas nécessairement porteur.',
  IFCWALLSTANDARDCASE: 'Un mur standard d\'épaisseur constante avec une coupe de matériaux en couches.',
  IFCSLAB: 'Une dalle ; un élément plat qui ferme un espace par le bas (plancher) ou par le haut (dalle de toiture).',
  IFCROOF: 'La couverture du sommet d\'un bâtiment qui le protège des intempéries.',
  IFCCOLUMN: 'Un élément généralement vertical qui transmet la charge de la structure supérieure vers les éléments inférieurs.',
  IFCBEAM: 'Un élément généralement horizontal qui résiste à la charge principalement par flexion.',
  IFCDOOR: 'Un élément de construction assurant le passage contrôlé des personnes, marchandises ou véhicules.',
  IFCWINDOW: 'Un élément de construction apportant lumière naturelle et air frais, à vantaux fixes ou ouvrants.',
  IFCSTAIR: 'L\'ensemble complet de l\'escalier permettant de passer à pied entre des étages de niveaux différents.',
  IFCSTAIRFLIGHT: 'Une volée continue de marches d\'escalier, non interrompue par un palier.',
  IFCRAILING: 'Un garde-corps placé le long des zones de circulation pour éviter les chutes ou collisions.',
  IFCFURNISHINGELEMENT: 'Terme général pour les objets de mobilier, mobiles ou intégrés.',
  IFCPLATE: 'Un élément plat d\'épaisseur constante, comme un panneau de façade ou métallique.',
  IFCMEMBER: 'Un élément porteur générique qui ne correspond pas à un type plus précis comme poteau ou poutre.',
  IFCCOVERING: 'Une couche de finition dépendante d\'un autre élément qu\'elle recouvre, comme un faux plafond ou un revêtement de sol.',
  IFCFOOTING: 'Un élément de fondation qui répartit la charge de la structure dans le sol.',
  IFCBUILDINGELEMENTPROXY: 'Un élément générique provisoire utilisé quand aucun type IFC spécifique ne s\'applique encore.',
  IFCFLOWSEGMENT: 'Un tronçon droit d\'un réseau technique (CVC, plomberie, etc.), comme un tube ou une gaine.',
  IFCFLOWTERMINAL: 'Le point terminal où un réseau technique rejoint son environnement, comme un robinet, une bouche d\'air ou une évacuation.',
  IFCGROUP: 'Un regroupement logique d\'objets sans position ni forme propre.',
};

const pt = {
  IFCPROJECT: 'O contexto de projeto de nível superior ao qual pertence toda a informação do modelo; contém definições comuns como unidades e sistema de coordenadas.',
  IFCSITE: 'O terreno sobre o qual o projeto é construído; define a sua localização e referência de altitude.',
  IFCBUILDING: 'Um edifício; junto com o terreno, os pisos e os espaços forma a estrutura espacial básica do modelo.',
  IFCBUILDINGSTOREY: 'Um piso do edifício; um nível horizontal que agrupa espaços de altura semelhante.',
  IFCSPACE: 'Uma área ou volume interior delimitado com uma função (uma divisão, corredor ou vão).',
  IFCWALL: 'Um elemento vertical ou quase vertical que separa ou delimita espaços; não precisa de ser portante.',
  IFCWALLSTANDARDCASE: 'Uma parede padrão de espessura constante com uma secção de materiais em camadas.',
  IFCSLAB: 'Uma laje; um elemento plano que fecha um espaço por baixo (piso) ou por cima (laje de cobertura).',
  IFCROOF: 'A cobertura no topo do edifício que o protege das intempéries.',
  IFCCOLUMN: 'Um elemento geralmente vertical que transmite a carga da estrutura superior para os elementos inferiores.',
  IFCBEAM: 'Um elemento geralmente horizontal que resiste à carga principalmente por flexão.',
  IFCDOOR: 'Um elemento construtivo que permite a passagem controlada de pessoas, mercadorias ou veículos.',
  IFCWINDOW: 'Um elemento construtivo para luz natural e ar fresco, com folhas fixas ou móveis.',
  IFCSTAIR: 'O conjunto completo da escada que permite passar a pé entre pisos de níveis diferentes.',
  IFCSTAIRFLIGHT: 'Um lanço contínuo de degraus, sem interrupção por um patamar.',
  IFCRAILING: 'Um corrimão/guarda-corpos colocado junto a zonas de circulação para evitar quedas ou colisões.',
  IFCFURNISHINGELEMENT: 'Termo geral para objetos de mobiliário, móveis ou embutidos.',
  IFCPLATE: 'Um elemento plano de espessura constante, como um painel de fachada ou metálico.',
  IFCMEMBER: 'Um elemento estrutural genérico que não se enquadra num tipo mais específico como pilar ou viga.',
  IFCCOVERING: 'Uma camada de acabamento dependente de outro elemento que reveste, como um teto falso ou um revestimento de piso.',
  IFCFOOTING: 'Um elemento de fundação que distribui a carga da estrutura para o solo.',
  IFCBUILDINGELEMENTPROXY: 'Um elemento genérico provisório usado quando ainda não existe um tipo IFC específico.',
  IFCFLOWSEGMENT: 'Um troço reto de uma instalação técnica (AVAC, canalização, etc.), como um tubo ou conduta.',
  IFCFLOWTERMINAL: 'O ponto final onde uma instalação técnica se liga ao ambiente, como uma torneira, saída de ar ou dreno.',
  IFCGROUP: 'Um agrupamento lógico de objetos sem posição ou forma própria.',
};

const it = {
  IFCPROJECT: 'Il contesto di progetto di livello superiore a cui appartengono tutte le informazioni del modello; contiene impostazioni comuni come unità e sistema di coordinate.',
  IFCSITE: 'Il terreno su cui viene costruito il progetto; ne definisce la posizione e il riferimento di quota.',
  IFCBUILDING: 'Un edificio; insieme al terreno, ai piani e agli spazi forma la struttura spaziale di base del modello.',
  IFCBUILDINGSTOREY: 'Un piano dell\'edificio; un livello orizzontale che raggruppa spazi di altezza simile.',
  IFCSPACE: 'Un\'area o volume interno delimitato con una funzione (una stanza, un corridoio o un vano).',
  IFCWALL: 'Un elemento verticale o quasi verticale che separa o delimita spazi; non deve necessariamente essere portante.',
  IFCWALLSTANDARDCASE: 'Una parete standard di spessore costante con una sezione di materiali stratificati.',
  IFCSLAB: 'Una soletta; un elemento piano che chiude uno spazio dal basso (solaio) o dall\'alto (soletta di copertura).',
  IFCROOF: 'La copertura sommitale di un edificio che lo protegge dagli agenti atmosferici.',
  IFCCOLUMN: 'Un elemento generalmente verticale che trasmette il carico della struttura superiore agli elementi sottostanti.',
  IFCBEAM: 'Un elemento generalmente orizzontale che resiste al carico principalmente per flessione.',
  IFCDOOR: 'Un elemento costruttivo che consente il passaggio controllato di persone, merci o veicoli.',
  IFCWINDOW: 'Un elemento costruttivo per luce naturale e aria fresca, con ante fisse o apribili.',
  IFCSTAIR: 'L\'intero assieme della scala che consente di passare a piedi tra piani di livello diverso.',
  IFCSTAIRFLIGHT: 'Una rampa continua di gradini, non interrotta da un pianerottolo.',
  IFCRAILING: 'Un parapetto posto lungo le zone di circolazione per prevenire cadute o collisioni.',
  IFCFURNISHINGELEMENT: 'Termine generale per gli oggetti di arredo, mobili o incorporati.',
  IFCPLATE: 'Un elemento piano di spessore costante, come un pannello di facciata o metallico.',
  IFCMEMBER: 'Un elemento strutturale generico che non rientra in un tipo più specifico come pilastro o trave.',
  IFCCOVERING: 'Uno strato di finitura dipendente da un altro elemento che ricopre, come un controsoffitto o una pavimentazione.',
  IFCFOOTING: 'Un elemento di fondazione che distribuisce il carico della struttura nel terreno.',
  IFCBUILDINGELEMENTPROXY: 'Un elemento generico provvisorio usato quando non esiste ancora un tipo IFC specifico.',
  IFCFLOWSEGMENT: 'Un tratto rettilineo di un impianto tecnico (HVAC, idraulico, ecc.), come un tubo o un condotto.',
  IFCFLOWTERMINAL: 'Il punto terminale in cui un impianto si collega all\'ambiente, come un rubinetto, una bocchetta o uno scarico.',
  IFCGROUP: 'Un raggruppamento logico di oggetti senza posizione o forma propria.',
};

const zh = {
  IFCPROJECT: '模型所有信息所属的最高层项目上下文，承载单位、坐标系统等通用设置。',
  IFCSITE: '项目所建造的地块；定义其位置和高程基准。',
  IFCBUILDING: '建筑物；与场地、楼层和空间一起构成模型的基本空间结构。',
  IFCBUILDINGSTOREY: '建筑楼层；汇集高度相近空间的水平层级。',
  IFCSPACE: '具有特定功能的有边界室内区域或体积（如房间、走廊或空腔）。',
  IFCWALL: '垂直或接近垂直、用于分隔或界定空间的墙体元素，不要求一定承重。',
  IFCWALLSTANDARDCASE: '厚度恒定、具有分层材料截面的标准类型墙体。',
  IFCSLAB: '楼板；从下方（楼层）或上方（屋面板）封闭空间的平面构件。',
  IFCROOF: '覆盖建筑物顶部、抵御天气影响的屋顶。',
  IFCCOLUMN: '通常竖直，将上部结构荷载传递至下方构件的柱。',
  IFCBEAM: '通常水平，主要通过抗弯来承受荷载的梁。',
  IFCDOOR: '为人员、货物或车辆提供受控通行的建筑构件——门。',
  IFCWINDOW: '提供自然采光和通风的建筑构件，可为固定或可开启扇——窗。',
  IFCSTAIR: '使人员能够在不同标高楼层间步行通过的整体楼梯。',
  IFCSTAIRFLIGHT: '未被休息平台打断的单个连续踏步段。',
  IFCRAILING: '设置在通行区域边缘、用于防止跌落或碰撞的栏杆。',
  IFCFURNISHINGELEMENT: '家具类物体的统称，无论可移动还是固定内嵌。',
  IFCPLATE: '厚度恒定的平面构件，如幕墙板或金属板。',
  IFCMEMBER: '不属于柱、梁等更具体类型的通用承重构件。',
  IFCCOVERING: '依附于并覆盖其他构件的饰面层，如吊顶或地面装饰层。',
  IFCFOOTING: '将结构荷载扩散传递至地基的基础构件。',
  IFCBUILDINGELEMENTPROXY: '尚无具体 IFC 类型定义时使用的通用占位构件。',
  IFCFLOWSEGMENT: '机电系统（暖通、给排水等）中的一段直管或风管。',
  IFCFLOWTERMINAL: '机电系统与外部环境相接的终端点，如水龙头、风口或地漏。',
  IFCGROUP: '没有自身位置或形状、按逻辑关系聚合对象的分组。',
};

export const IFC_GLOSSARY = { tr, en, de, ar, ru, es, fr, pt, it, zh };

/** IFC tip kodu icin verilen dilde sozluk aciklamasini dondurur; yoksa Turkce'ye, o da yoksa null'a duser. */
export function glossaryDescription(language, type) {
  if (!type) return null;
  const code = String(type).toUpperCase();
  const dict = IFC_GLOSSARY[language] || tr;
  return dict[code] || tr[code] || null;
}

/** Sozlukte tanimli tum tip kodlarini dondurur (ifcTypes.js MAP ile ayni kume). */
export function glossaryCodes() {
  return Object.keys(tr);
}
